// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOqQ1x6diBeDmBJNDqE8Ls7cVIhUYlAFY',
    appId: '1:780395595083:web:cb7d16e43db5070ec114ce',
    messagingSenderId: '780395595083',
    projectId: 'stokall',
    authDomain: 'stokall.firebaseapp.com',
    storageBucket: 'stokall.firebasestorage.app',
    measurementId: 'G-MEXW9T63KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ncuzGnCa9sqN5jXUyOD8EGfELyqOjHU',
    appId: '1:780395595083:android:c628766736bd9f76c114ce',
    messagingSenderId: '780395595083',
    projectId: 'stokall',
    storageBucket: 'stokall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBojgyT6tPca4j5us1jND1gflHi0PyNoE8',
    appId: '1:780395595083:ios:7c2ade6152175714c114ce',
    messagingSenderId: '780395595083',
    projectId: 'stokall',
    storageBucket: 'stokall.firebasestorage.app',
    androidClientId: '780395595083-co8u9439m8q7mgrql1ohi1lqunnnvc5g.apps.googleusercontent.com',
    iosClientId: '780395595083-815nt44njf6j6t11aovjn4nq6k330kqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.stokAll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBojgyT6tPca4j5us1jND1gflHi0PyNoE8',
    appId: '1:780395595083:ios:7c2ade6152175714c114ce',
    messagingSenderId: '780395595083',
    projectId: 'stokall',
    storageBucket: 'stokall.firebasestorage.app',
    androidClientId: '780395595083-co8u9439m8q7mgrql1ohi1lqunnnvc5g.apps.googleusercontent.com',
    iosClientId: '780395595083-815nt44njf6j6t11aovjn4nq6k330kqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.stokAll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOqQ1x6diBeDmBJNDqE8Ls7cVIhUYlAFY',
    appId: '1:780395595083:web:33c345f1e8637e2fc114ce',
    messagingSenderId: '780395595083',
    projectId: 'stokall',
    authDomain: 'stokall.firebaseapp.com',
    storageBucket: 'stokall.firebasestorage.app',
    measurementId: 'G-7N7K7SDJG5',
  );
}
